# Generated by Django 4.0.4 on 2022-04-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allUsers', '0002_contactpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/img/cartoon-boy-images-11.jpg', upload_to='profile_pictures'),
        ),
    ]
