# Generated by Django 4.0.4 on 2022-04-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allUsers', '0003_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/img/cartoon-boy-images-11.jpg', upload_to='profile_pictures'),
        ),
    ]
